# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
<img src="https://www.google.com/search?q=Welcome&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjLtpia4-jUAhWI6SYKHYTdDC0Q_AUICigB&biw=1400&bih=902#imgrc=Hz844TkF2HfHrM:&spf=1498935857408">
# Site settings
title: Welcome To My Website
description: > # this means to ignore newlines until "baseurl:"
  Hello this is my first website so this is a test you can look at it theres not much to do so have a nice day and goodbye.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://demon2007.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: Demon2007
# Build settings
markdown: kramdown
